name: Build and Push Docker Image  # Workflow name

on:
  push:
    branches: [ "main" ]  # Trigger on pushes to 'main'
  pull_request:
    branches: [ "main" ]  # Trigger on pull requests to 'main'

jobs:
  build_and_push:
    runs-on: ubuntu-latest  # Use the latest Ubuntu environment
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4  # Check out the repository code
    
    - name: Docker Login  # Securely log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_PASSWORD }}" | docker login \
        -u "${{ secrets.DOCKER_HUB_USERNAME }}" \
        --password-stdin
    
    - name: Build Docker Image
      run: |
        docker build -t my-docker-image:latest .  # Build the Docker image from the root context
    
    - name: Tag Docker Image  # Tag the built image with the Docker Hub repository
      run: |
        docker tag my-docker-image:latest "${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-image:latest"
    
    - name: Push Docker Image  # Push the image to Docker Hub
      run: |
        docker push "${{ secrets.DOCKER_HUB_USERNAME }}/my-docker-image:latest"
